background="#232136"
text="#e0def4"
subtle="#6e6a86"
warning-text="#eb6f92"
text-special-one="#9ccfd8"
text-special-two="#c4a7e7"
top-bar-background="#393552"
top-bar-text="#e0def4"
status-bar-background="#2a273f"
status-bar-text="#908caa"
status-bar-view-background="#3e8fb0"
status-bar-view-text="#e0def4"
list-selected-background="#44415a"
list-selected-text="#e0def4"
